swcr:
  swcr_velocity_controller:
    type: "diff_drive_controller/DiffDriveController"

    left_wheel: ['wheelfl_joint', 'wheelbl_joint']
    right_wheel: ['wheelfr_joint', 'wheelbr_joint']
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    wheel_separation : 0.31

  
    base_frame_id: base_footprint
    cmd_vel_timeout: 0.25
    enable_odom_tf: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.2   # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.6   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 6.0   # rad/s^2
